//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homepage.wwwroot.files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ButtonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ButtonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Homepage.wwwroot.files.ButtonStrings", typeof(ButtonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Current Bid.
        /// </summary>
        internal static string Accept_Current_Bid {
            get {
                return ResourceManager.GetString("Accept Current Bid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Current Offer.
        /// </summary>
        internal static string Accept_Current_Offer {
            get {
                return ResourceManager.GetString("Accept Current Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Offer.
        /// </summary>
        internal static string Accept_Offer {
            get {
                return ResourceManager.GetString("Accept Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Trade Offer.
        /// </summary>
        internal static string Accept_Trade_Offer {
            get {
                return ResourceManager.GetString("Accept Trade Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        internal static string Add_Category {
            get {
                return ResourceManager.GetString("Add Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Subcategory.
        /// </summary>
        internal static string Add_Subcategory {
            get {
                return ResourceManager.GetString("Add Subcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach Logs.
        /// </summary>
        internal static string Attach_Logs {
            get {
                return ResourceManager.GetString("Attach Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Categories.
        /// </summary>
        internal static string Back_to_Categories {
            get {
                return ResourceManager.GetString("Back to Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker Fees.
        /// </summary>
        internal static string Broker_Fees {
            get {
                return ResourceManager.GetString("Broker Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes At.
        /// </summary>
        internal static string Closes_At {
            get {
                return ResourceManager.GetString("Closes At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm This Purchase.
        /// </summary>
        internal static string Confirm_This_Purchase {
            get {
                return ResourceManager.GetString("Confirm This Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm This Sale.
        /// </summary>
        internal static string Confirm_This_Sale {
            get {
                return ResourceManager.GetString("Confirm This Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Bid.
        /// </summary>
        internal static string Custom_Bid {
            get {
                return ResourceManager.GetString("Custom Bid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease.
        /// </summary>
        internal static string Decrease {
            get {
                return ResourceManager.GetString("Decrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Balance.
        /// </summary>
        internal static string Default_Balance {
            get {
                return ResourceManager.GetString("Default Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Minimum Bid Limit.
        /// </summary>
        internal static string Default_Minimum_Bid_Limit {
            get {
                return ResourceManager.GetString("Default Minimum Bid Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default to.
        /// </summary>
        internal static string Default_to {
            get {
                return ResourceManager.GetString("Default to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Entry Fees.
        /// </summary>
        internal static string Disable_Entry_Fees {
            get {
                return ResourceManager.GetString("Disable Entry Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donations.
        /// </summary>
        internal static string Donations {
            get {
                return ResourceManager.GetString("Donations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early Acceptance.
        /// </summary>
        internal static string Early_Acceptance {
            get {
                return ResourceManager.GetString("Early Acceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Details.
        /// </summary>
        internal static string Edit_Details {
            get {
                return ResourceManager.GetString("Edit Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Item.
        /// </summary>
        internal static string Edit_Item {
            get {
                return ResourceManager.GetString("Edit Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Listing.
        /// </summary>
        internal static string Edit_Listing {
            get {
                return ResourceManager.GetString("Edit Listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Entry Fees.
        /// </summary>
        internal static string Enable_Entry_Fees {
            get {
                return ResourceManager.GetString("Enable Entry Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Fees.
        /// </summary>
        internal static string Entry_Fees {
            get {
                return ResourceManager.GetString("Entry Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend.
        /// </summary>
        internal static string Extend {
            get {
                return ResourceManager.GetString("Extend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Bid.
        /// </summary>
        internal static string Highest_Bid {
            get {
                return ResourceManager.GetString("Highest Bid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase.
        /// </summary>
        internal static string Increase {
            get {
                return ResourceManager.GetString("Increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inline Results.
        /// </summary>
        internal static string Inline_Results {
            get {
                return ResourceManager.GetString("Inline Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Align.
        /// </summary>
        internal static string Left_Align {
            get {
                return ResourceManager.GetString("Left Align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing Fees.
        /// </summary>
        internal static string Listing_Fees {
            get {
                return ResourceManager.GetString("Listing Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Bid Button.
        /// </summary>
        internal static string Min_Bid_Button {
            get {
                return ResourceManager.GetString("Min Bid Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negotiate Offer.
        /// </summary>
        internal static string Negotiate_Offer {
            get {
                return ResourceManager.GetString("Negotiate Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens At.
        /// </summary>
        internal static string Opens_At {
            get {
                return ResourceManager.GetString("Opens At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recall Listings.
        /// </summary>
        internal static string Recall_Listings {
            get {
                return ResourceManager.GetString("Recall Listings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Offer.
        /// </summary>
        internal static string Reject_Offer {
            get {
                return ResourceManager.GetString("Reject Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Auction Listing.
        /// </summary>
        internal static string Remove_Auction_Listing {
            get {
                return ResourceManager.GetString("Remove Auction Listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Category.
        /// </summary>
        internal static string Remove_Category {
            get {
                return ResourceManager.GetString("Remove Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Channel.
        /// </summary>
        internal static string Remove_Channel {
            get {
                return ResourceManager.GetString("Remove Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Default Balance.
        /// </summary>
        internal static string Remove_Default_Balance {
            get {
                return ResourceManager.GetString("Remove Default Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Market Listing.
        /// </summary>
        internal static string Remove_Market_Listing {
            get {
                return ResourceManager.GetString("Remove Market Listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Room.
        /// </summary>
        internal static string Remove_Room {
            get {
                return ResourceManager.GetString("Remove Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Subcategory.
        /// </summary>
        internal static string Remove_Subcategory {
            get {
                return ResourceManager.GetString("Remove Subcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Trade Listing.
        /// </summary>
        internal static string Remove_Trade_Listing {
            get {
                return ResourceManager.GetString("Remove Trade Listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Align.
        /// </summary>
        internal static string Right_Align {
            get {
                return ResourceManager.GetString("Right Align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sealed Payout.
        /// </summary>
        internal static string Sealed_Payout {
            get {
                return ResourceManager.GetString("Sealed Payout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Highest.
        /// </summary>
        internal static string Second_Highest {
            get {
                return ResourceManager.GetString("Second Highest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Default.
        /// </summary>
        internal static string Set_Default {
            get {
                return ResourceManager.GetString("Set Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Default Balance.
        /// </summary>
        internal static string Set_Default_Balance {
            get {
                return ResourceManager.GetString("Set Default Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Duration Limits.
        /// </summary>
        internal static string Set_Duration_Limits {
            get {
                return ResourceManager.GetString("Set Duration Limits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Listing Limits.
        /// </summary>
        internal static string Set_Listing_Limits {
            get {
                return ResourceManager.GetString("Set Listing Limits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shill Bidding.
        /// </summary>
        internal static string Shill_Bidding {
            get {
                return ResourceManager.GetString("Shill Bidding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Bot Review.
        /// </summary>
        internal static string Submit_Bot_Review {
            get {
                return ResourceManager.GetString("Submit Bot Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Server.
        /// </summary>
        internal static string Support_Server {
            get {
                return ResourceManager.GetString("Support Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle.
        /// </summary>
        internal static string Toggle {
            get {
                return ResourceManager.GetString("Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Confirmation.
        /// </summary>
        internal static string Transaction_Confirmation {
            get {
                return ResourceManager.GetString("Transaction Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Bid.
        /// </summary>
        internal static string Undo_Bid {
            get {
                return ResourceManager.GetString("Undo Bid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Hours.
        /// </summary>
        internal static string Update_Hours {
            get {
                return ResourceManager.GetString("Update Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Item.
        /// </summary>
        internal static string View_Item {
            get {
                return ResourceManager.GetString("View Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Settings.
        /// </summary>
        internal static string View_Settings {
            get {
                return ResourceManager.GetString("View Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw.
        /// </summary>
        internal static string Withdraw {
            get {
                return ResourceManager.GetString("Withdraw", resourceCulture);
            }
        }
    }
}
